services:
  db:
    image: postgres:18-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports: ["5432:5432"]
    volumes: [pg:/var/lib/postgresql/data]
volumes:
  pg: {}